In [2]:
import numpy as np

Complemento, ejercicio 5, clase 5

In [1]:
#Comprobación que las matrices de Pauli son ortogonales

#Primero definamos las matrices:
import numpy as np

# Definición de matrices de Pauli
sigma0 = np.array([[1, 0], [0, 1]], dtype=complex)
sigma1 = np.array([[0, 1], [1, 0]], dtype=complex)
sigma2 = np.array([[0, -1j], [1j, 0]], dtype=complex)
sigma3 = np.array([[1, 0], [0, -1]], dtype=complex)

paulis = [sigma0, sigma1, sigma2, sigma3]
names  = ["σ0", "σ1", "σ2", "σ3"]

# Producto interno: <A,B> = Tr(A† B)
def inner_product(A, B):
    return np.trace(A.conj().T @ B)

# Construir matriz de Gram
G = np.zeros((4,4), dtype=complex)
for i in range(4):
    for j in range(4):
        G[i,j] = inner_product(paulis[i], paulis[j])

print("Matriz de Gram (producto interno entre Pauli):")
print(np.real_if_close(G))   # Elimina restos numéricos tipo 1e-16




Matriz de Gram (producto interno entre Pauli):
[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]
